steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'asia.gcr.io/bangalore-sandbox/weather-forecast-api'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'asia.gcr.io/bangalore-sandbox/weather-forecast-api'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - weather-forecast-api
      - '--image'
      - 'asia.gcr.io/bangalore-sandbox/weather-forecast-api'
      - '--region'
      - 'asia-south1'     
    entrypoint: gcloud
timeout: 1200s
images:
  - 'asia.gcr.io/bangalore-sandbox/weather-forecast-api'